version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api-node:
    build: ./api-node
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - PYTHON_API_URL=http://api-python:5000
    depends_on:
      - redis
      - api-python

  api-python:
    build: ./api-python
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - redis
      - rabbitmq

  api-php:
    build: ./api-php
    ports:
      - "8001:80"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

volumes:
  redis_data:
  rabbitmq_data:
